
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_customer_raw
COMMENT "Load customer table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.customer_raw);

CREATE OR REFRESH MATERIALIZED VIEW v_customer_migration
COMMENT "Load customer table from migration schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
LIVE.acme_edw_dev.edw_old.customer;


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_customer_bronze_cleaned
COMMENT "SQL transform: customer_bronze_incremental_cleanse"AS
SELECT
  xxhash64(c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment) as customer_key,
  c_custkey as customer_id,
  c_name as name,
  c_address as address,
  c_nationkey as nation_id,
  c_phone as phone,
  c_acctbal as account_balance,
  c_mktsegment as market_segment,
  c_comment as comment,
  last_modified_dt,
  * EXCEPT(c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment,last_modified_dt,_rescued_data)
FROM stream(v_customer_raw);


CREATE OR REFRESH VIEW v_customer_migration_cleaned
COMMENT "SQL transform: customer_migration_cleanse"AS
SELECT
  xxhash64(c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment) as customer_key,
  c_custkey as customer_id,
  c_name as name,
  c_address as address,
  c_nationkey as nation_id,
  c_phone as phone,
  c_acctbal as account_balance,
  c_mktsegment as market_segment,
  c_comment as comment,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  'MIGRATION' as _source_file_path,
  * EXCEPT(c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment,last_modified_dt)
FROM v_customer_migration;





# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.customerCOMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_customer"
AS SELECT * FROM STREAM(LIVE.v_customer_migration_cleaned);
CREATE OR REFRESH STREAMING TABLE v_customer_bronze_DQE_to_customer_flow (
  COMMENT "Flow to insert data from v_customer_bronze_DQE into customer"
)
AS SELECT * FROM STREAM(LIVE.v_customer_bronze_DQE);

APPLY CHANGES INTO LIVE.acme_edw_dev.edw_bronze.customer
FROM STREAM(LIVE.v_customer_bronze_DQE_to_customer_flow)
KEYS()
SEQUENCE BY 1
COLUMNS *;