
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_lineitem_middle_east_raw
COMMENT "Load lineitem table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.lineitem_middle_east_raw);


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_lineitem_middle_east_bronze_cleaned
COMMENT "SQL transform: lineitem_bronze_cleanse"AS
SELECT
  l_orderkey as order_id,
  l_partkey as part_id,
  l_suppkey as supplier_id,
  l_linenumber as line_number,
  l_quantity as quantity,
  l_extendedprice as extended_price,
  l_discount as discount,
  l_tax as tax,
  l_returnflag as return_flag,
  l_linestatus as line_status,
  l_shipdate as ship_date,
  l_commitdate as commit_date,
  l_receiptdate as receipt_date,
  l_shipinstruct as ship_instruct,
  l_shipmode as ship_mode,
  l_comment as comment,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  * EXCEPT(l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment,last_modified_dt,_rescued_data)
FROM stream(v_lineitem_middle_east_raw);





# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.lineitemCOMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_lineitem"
AS SELECT * FROM STREAM(LIVE.v_lineitem_middle_east_bronze_DQE);