
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_nation_raw
COMMENT "Load nation table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.nation_raw);


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_nation_bronze_cleaned
COMMENT "SQL transform: nation_bronze_incremental_cleanse"AS
SELECT
  xxhash64(n_name,n_regionkey,n_comment) as nation_key,
  n_name as name,
  n_regionkey as region_id,
  n_comment as comment,
  * EXCEPT(n_nationkey, n_name, n_regionkey, n_comment,_rescued_data)
FROM stream(v_nation_raw);



# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.nationCOMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_nation"
AS SELECT * FROM STREAM(LIVE.v_nation_bronze_cleaned);