
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_part_raw
COMMENT "Load part table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.part_raw);

CREATE OR REFRESH MATERIALIZED VIEW v_part_migration
COMMENT "Load part table from migration schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
LIVE.acme_edw_dev.edw_old.part;


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_part_bronze_cleaned
COMMENT "SQL transform: part_bronze_incremental_cleanse"AS
SELECT
  xxhash64(p_partkey,p_name,p_mfgr,p_brand,p_type,p_size,p_container,p_retailprice,p_comment) as part_key,
  p_partkey as part_id,
  p_name as name,
  p_mfgr as manufacturer,
  p_brand as brand,
  p_type as type,
  p_size as size,
  p_container as container,
  p_retailprice as retail_price,
  p_comment as comment,
  cast(extract_timestamp as TIMESTAMP) as extract_timestamp,
  source_system,
  cast(source_system_timestamp as TIMESTAMP) as source_system_timestamp,
  split(split(_source_file_path, '/part/')[1], '/')[0] as snapshot_id,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  * EXCEPT(p_partkey, p_name, p_mfgr, p_brand, p_type, p_size, p_container, p_retailprice, p_comment, last_modified_dt,_rescued_data,extract_timestamp,source_system,source_system_timestamp)
FROM stream(v_part_raw);


CREATE OR REFRESH VIEW v_part_migration_bronze_cleaned
COMMENT "SQL transform: part_migration_bronze_cleanse"AS
SELECT
  xxhash64(p_partkey,p_name,p_mfgr,p_brand,p_type,p_size,p_container,p_retailprice,p_comment) as part_key,
  p_partkey as part_id,
  p_name as name,
  p_mfgr as manufacturer,
  p_brand as brand,
  p_type as type,
  p_size as size,
  p_container as container,
  p_retailprice as retail_price,
  p_comment as comment,
  now() as extract_timestamp,
  "DW MIGRATION" as source_system,
  null as source_system_timestamp,
  '2019-W01' as snapshot_id,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  'MIGRATION' as _source_file_path,
  * EXCEPT(p_partkey, p_name, p_mfgr, p_brand, p_type, p_size, p_container, p_retailprice, p_comment, last_modified_dt)
FROM v_part_migration;



# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.partPARTITIONED BY (snapshot_id)COMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_part"
AS SELECT * FROM STREAM(LIVE.v_part_bronze_cleaned);
CREATE OR REFRESH STREAMING TABLE v_part_migration_bronze_cleaned_to_part_flow (
  COMMENT "Flow to insert data from v_part_migration_bronze_cleaned into part"
)
AS SELECT * FROM STREAM(LIVE.v_part_migration_bronze_cleaned);

APPLY CHANGES INTO LIVE.acme_edw_dev.edw_bronze.part
FROM STREAM(LIVE.v_part_migration_bronze_cleaned_to_part_flow)
KEYS()
SEQUENCE BY 1
COLUMNS *;