
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_partsupp_raw
COMMENT "Load partsupp table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.partsupp_raw);

CREATE OR REFRESH MATERIALIZED VIEW v_partsupp_migration
COMMENT "Load partsupp table from migration schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
LIVE.acme_edw_dev.edw_old.partsupp;


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_partsupp_bronze_cleaned
COMMENT "SQL transform: partsupp_bronze_incremental_cleanse"AS
SELECT
  xxhash64(ps_partkey,ps_suppkey,ps_availqty,ps_supplycost,ps_comment) as partsupp_key,
  ps_partkey as part_id,
  ps_suppkey as supplier_id,
  ps_availqty as available_quantity,
  cast(ps_supplycost as decimal(18,2)) as supply_cost,
  ps_comment as comment,
  split(split(_source_file_path, '/partsupp/')[1], '/')[0] as snapshot_id,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  * EXCEPT(ps_partkey, ps_suppkey, ps_availqty, ps_supplycost, ps_comment, last_modified_dt,_rescued_data)
FROM stream(v_partsupp_raw);


CREATE OR REFRESH VIEW v_partsupp_migration_bronze_cleaned
COMMENT "SQL transform: partsupp_migration_bronze_cleanse"AS
SELECT
  xxhash64(ps_partkey,ps_suppkey,ps_availqty,ps_supplycost,ps_comment) as partsupp_key,
  ps_partkey as part_id,
  ps_suppkey as supplier_id,
  ps_availqty as available_quantity,
  ps_supplycost as supply_cost,
  ps_comment as comment,
  '2019-W01' as snapshot_id,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  'MIGRATION' as _source_file_path,
  * EXCEPT(ps_partkey, ps_suppkey, ps_availqty, ps_supplycost, ps_comment, last_modified_dt)
FROM v_partsupp_migration;



# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.partsuppPARTITIONED BY (snapshot_id)COMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_partsupp"
AS SELECT * FROM STREAM(LIVE.v_partsupp_bronze_cleaned);
CREATE OR REFRESH STREAMING TABLE v_partsupp_migration_bronze_cleaned_to_partsupp_flow (
  COMMENT "Flow to insert data from v_partsupp_migration_bronze_cleaned into partsupp"
)
AS SELECT * FROM STREAM(LIVE.v_partsupp_migration_bronze_cleaned);

APPLY CHANGES INTO LIVE.acme_edw_dev.edw_bronze.partsupp
FROM STREAM(LIVE.v_partsupp_migration_bronze_cleaned_to_partsupp_flow)
KEYS()
SEQUENCE BY 1
COLUMNS *;