
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_region_raw
COMMENT "Load region table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.region_raw);


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_region_bronze_cleaned
COMMENT "SQL transform: region_bronze_incremental_cleanse"AS
SELECT
  xxhash64(r_regionkey,r_name,r_comment) as region_key,
  r_regionkey as region_id,
  r_name as name,
  r_comment as comment,
  * EXCEPT(r_regionkey, r_name, r_comment,_rescued_data)
FROM stream(v_region_raw);



# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.regionCOMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_region"
AS SELECT * FROM STREAM(LIVE.v_region_bronze_cleaned);