
# ============================================================================
# SOURCE VIEWS
# ============================================================================

CREATE OR REFRESH STREAMING TABLE v_supplier_raw
COMMENT "Load supplier table from raw schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
STREAM(LIVE.acme_edw_dev.edw_raw.supplier_raw);

CREATE OR REFRESH MATERIALIZED VIEW v_supplier_migration
COMMENT "Load supplier table from migration schema"
AS SELECT
*  , F.current_timestamp() AS _processing_timestampFROM
LIVE.acme_edw_dev.edw_old.supplier;


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================

CREATE OR REFRESH VIEW v_supplier_bronze_cleaned
COMMENT "SQL transform: supplier_bronze_incremental_cleanse"AS
SELECT
  xxhash64(s_suppkey,s_name,s_address,s_nationkey,s_phone,s_acctbal,s_comment) as supplier_key,
  s_suppkey as supplier_id,
  s_name as name,
  s_address as address,
  s_nationkey as nation_id,
  s_phone as phone,
  cast(s_acctbal as decimal(18,2)) as account_balance,
  s_comment as comment,
  split(split(_source_file_path, '/supplier/')[1], '/')[0] as snapshot_id,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  * EXCEPT(s_suppkey, s_name, s_address, s_nationkey, s_phone, s_acctbal, s_comment, last_modified_dt,_rescued_data)
FROM stream(v_supplier_raw);


CREATE OR REFRESH VIEW v_supplier_migration_bronze_cleaned
COMMENT "SQL transform: supplier_migration_bronze_incremental_cleanse"AS
SELECT
  xxhash64(s_suppkey,s_name,s_address,s_nationkey,s_phone,s_acctbal,s_comment) as supplier_key,
  s_suppkey as supplier_id,
  s_name as name,
  s_address as address,
  s_nationkey as nation_id,
  s_phone as phone,
  s_acctbal as account_balance,
  s_comment as comment,
  '2019-W01' as snapshot_id,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  'MIGRATION' as _source_file_path,
  * EXCEPT(s_suppkey, s_name, s_address, s_nationkey, s_phone, s_acctbal, s_comment, last_modified_dt)
FROM v_supplier_migration;



# ============================================================================
# TARGET TABLES
# ============================================================================


-- Create the streaming table from the primary source
CREATE OR REFRESH STREAMING TABLE acme_edw_dev.edw_bronze.supplierPARTITIONED BY (snapshot_id)COMMENT "Generated by Lakehouse Plumber: write_acme_edw_dev_edw_bronze_supplier"
AS SELECT * FROM STREAM(LIVE.v_supplier_bronze_cleaned);
CREATE OR REFRESH STREAMING TABLE v_supplier_migration_bronze_cleaned_to_supplier_flow (
  COMMENT "Flow to insert data from v_supplier_migration_bronze_cleaned into supplier"
)
AS SELECT * FROM STREAM(LIVE.v_supplier_migration_bronze_cleaned);

APPLY CHANGES INTO LIVE.acme_edw_dev.edw_bronze.supplier
FROM STREAM(LIVE.v_supplier_migration_bronze_cleaned_to_supplier_flow)
KEYS()
SEQUENCE BY 1
COLUMNS *;