-- Gold Layer - Customer 360 View
-- Comprehensive customer analytics combining all touchpoints and behaviors
-- Generated by Nexa Platform - DO NOT EDIT MANUALLY

CREATE OR REFRESH MATERIALIZED VIEW gold_analytics.customer_360 (
  CONSTRAINT valid_customer_id EXPECT (customer_id IS NOT NULL) ON VIOLATION FAIL UPDATE,
  CONSTRAINT valid_metrics EXPECT (total_transactions >= 0 AND lifetime_value >= 0) ON VIOLATION FAIL UPDATE
)
PARTITIONED BY (customer_segment, value_tier)
CLUSTER BY (loyalty_tier, days_since_last_purchase)
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true',
  'pipelines.reset.allowed' = 'false'
)
AS
WITH transaction_summary AS (
  -- Comprehensive transaction metrics by customer
  SELECT 
    customer_id,
    
    -- Transaction counts and frequency
    COUNT(*) as total_transactions,
    COUNT(DISTINCT transaction_date) as active_days,
    COUNT(DISTINCT transaction_month) as active_months,
    COUNT(DISTINCT store_id) as stores_visited,
    
    -- Financial metrics
    SUM(total_amount) as lifetime_value,
    AVG(total_amount) as avg_transaction_value,
    MIN(total_amount) as min_transaction_value,
    MAX(total_amount) as max_transaction_value,
    STDDEV(total_amount) as transaction_value_stddev,
    
    -- Product and quantity metrics
    SUM(total_quantity) as total_items_purchased,
    AVG(total_quantity) as avg_items_per_transaction,
    SUM(item_count) as total_line_items,
    AVG(item_count) as avg_line_items_per_transaction,
    
    -- Timing patterns
    MIN(transaction_timestamp) as first_transaction_date,
    MAX(transaction_timestamp) as last_transaction_date,
    COUNT(CASE WHEN time_of_day = 'Morning' THEN 1 END) as morning_transactions,
    COUNT(CASE WHEN time_of_day = 'Afternoon' THEN 1 END) as afternoon_transactions,
    COUNT(CASE WHEN time_of_day = 'Evening' THEN 1 END) as evening_transactions,
    COUNT(CASE WHEN time_of_day = 'Night' THEN 1 END) as night_transactions,
    
    -- Day of week preferences
    COUNT(CASE WHEN day_name = 'Monday' THEN 1 END) as monday_transactions,
    COUNT(CASE WHEN day_name = 'Tuesday' THEN 1 END) as tuesday_transactions,
    COUNT(CASE WHEN day_name = 'Wednesday' THEN 1 END) as wednesday_transactions,
    COUNT(CASE WHEN day_name = 'Thursday' THEN 1 END) as thursday_transactions,
    COUNT(CASE WHEN day_name = 'Friday' THEN 1 END) as friday_transactions,
    COUNT(CASE WHEN day_name = 'Saturday' THEN 1 END) as saturday_transactions,
    COUNT(CASE WHEN day_name = 'Sunday' THEN 1 END) as sunday_transactions,
    
    -- Payment method preferences
    COUNT(DISTINCT payment_method_clean) as payment_methods_used,
    COUNT(CASE WHEN payment_method_clean = 'CREDIT' THEN 1 END) as credit_transactions,
    COUNT(CASE WHEN payment_method_clean = 'DEBIT' THEN 1 END) as debit_transactions,
    COUNT(CASE WHEN payment_method_clean = 'CASH' THEN 1 END) as cash_transactions,
    COUNT(CASE WHEN payment_method_clean = 'MOBILE' THEN 1 END) as mobile_transactions,
    
    -- Discount and promotion usage
    COUNT(CASE WHEN discount_applied THEN 1 END) as discounted_transactions,
    SUM(CASE WHEN discount_applied THEN discount_amount ELSE 0 END) as total_discounts_received,
    COUNT(CASE WHEN promotion_count > 0 THEN 1 END) as promoted_transactions,
    
    -- Loyalty program engagement
    SUM(loyalty_points_earned) as total_points_earned,
    SUM(loyalty_points_redeemed) as total_points_redeemed,
    COUNT(CASE WHEN loyalty_points_earned > 0 THEN 1 END) as point_earning_transactions,
    COUNT(CASE WHEN loyalty_points_redeemed > 0 THEN 1 END) as point_redemption_transactions,
    
    -- Transaction size patterns
    COUNT(CASE WHEN transaction_size = 'Small' THEN 1 END) as small_transactions,
    COUNT(CASE WHEN transaction_size = 'Medium' THEN 1 END) as medium_transactions,
    COUNT(CASE WHEN transaction_size = 'Large' THEN 1 END) as large_transactions,
    COUNT(CASE WHEN transaction_size = 'Very Large' THEN 1 END) as very_large_transactions
    
  FROM silver_curated.pos_transactions_cleansed
  WHERE customer_id IS NOT NULL
  GROUP BY customer_id
),

recent_behavior AS (
  -- Recent behavior metrics (last 30, 90, 365 days)
  SELECT 
    customer_id,
    
    -- 30-day metrics
    COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 30 DAYS THEN 1 END) as transactions_30d,
    SUM(CASE WHEN transaction_date >= current_date() - INTERVAL 30 DAYS THEN total_amount ELSE 0 END) as spend_30d,
    COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 30 DAYS THEN DISTINCT transaction_date END) as active_days_30d,
    
    -- 90-day metrics  
    COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 90 DAYS THEN 1 END) as transactions_90d,
    SUM(CASE WHEN transaction_date >= current_date() - INTERVAL 90 DAYS THEN total_amount ELSE 0 END) as spend_90d,
    COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 90 DAYS THEN DISTINCT transaction_date END) as active_days_90d,
    
    -- 365-day metrics
    COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 365 DAYS THEN 1 END) as transactions_365d,
    SUM(CASE WHEN transaction_date >= current_date() - INTERVAL 365 DAYS THEN total_amount ELSE 0 END) as spend_365d,
    COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 365 DAYS THEN DISTINCT transaction_date END) as active_days_365d,
    
    -- Recency
    DATEDIFF(current_date(), MAX(transaction_date)) as days_since_last_purchase
    
  FROM silver_curated.pos_transactions_cleansed  
  WHERE customer_id IS NOT NULL
  GROUP BY customer_id
),

customer_trends AS (
  -- Customer behavior trends and seasonality
  SELECT 
    customer_id,
    
    -- Monthly spend trend (last 6 months)
    AVG(CASE WHEN transaction_date >= LAST_DAY(current_date() - INTERVAL 6 MONTHS) THEN total_amount END) as avg_monthly_spend_6m,
    AVG(CASE WHEN transaction_date >= LAST_DAY(current_date() - INTERVAL 12 MONTHS) THEN total_amount END) as avg_monthly_spend_12m,
    
    -- Seasonality patterns
    AVG(CASE WHEN MONTH(transaction_date) IN (12, 1, 2) THEN total_amount END) as avg_winter_spend,
    AVG(CASE WHEN MONTH(transaction_date) IN (3, 4, 5) THEN total_amount END) as avg_spring_spend,
    AVG(CASE WHEN MONTH(transaction_date) IN (6, 7, 8) THEN total_amount END) as avg_summer_spend,
    AVG(CASE WHEN MONTH(transaction_date) IN (9, 10, 11) THEN total_amount END) as avg_fall_spend,
    
    -- Growth indicators
    CASE 
      WHEN COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 90 DAYS THEN 1 END) > 
           COUNT(CASE WHEN transaction_date BETWEEN current_date() - INTERVAL 180 DAYS AND current_date() - INTERVAL 90 DAYS THEN 1 END)
      THEN 'Growing'
      WHEN COUNT(CASE WHEN transaction_date >= current_date() - INTERVAL 90 DAYS THEN 1 END) < 
           COUNT(CASE WHEN transaction_date BETWEEN current_date() - INTERVAL 180 DAYS AND current_date() - INTERVAL 90 DAYS THEN 1 END)
      THEN 'Declining'  
      ELSE 'Stable'
    END as trend_direction
    
  FROM silver_curated.pos_transactions_cleansed
  WHERE customer_id IS NOT NULL
  GROUP BY customer_id
)

SELECT 
  -- Customer identification and profile
  cp.customer_id,
  cp.full_name,
  cp.email_clean as email,
  cp.phone_standardized as phone,
  cp.city,
  cp.state_province,
  cp.country_code,
  
  -- Demographics
  cp.age_years,
  cp.age_group,
  cp.gender_standardized as gender,
  cp.registration_date,
  cp.customer_tenure_days,
  
  -- Current status and engagement  
  cp.is_active,
  cp.loyalty_tier,
  cp.loyalty_points_balance,
  cp.customer_segment,
  cp.value_tier,
  cp.engagement_score,
  cp.profile_completeness,
  
  -- Transaction behavior (lifetime)
  COALESCE(ts.total_transactions, 0) as total_transactions,
  COALESCE(ts.lifetime_value, 0) as lifetime_value,
  COALESCE(ts.avg_transaction_value, 0) as avg_transaction_value,
  COALESCE(ts.min_transaction_value, 0) as min_transaction_value,
  COALESCE(ts.max_transaction_value, 0) as max_transaction_value,
  COALESCE(ts.transaction_value_stddev, 0) as transaction_value_stddev,
  
  -- Product and shopping behavior
  COALESCE(ts.total_items_purchased, 0) as total_items_purchased,
  COALESCE(ts.avg_items_per_transaction, 0) as avg_items_per_transaction,
  COALESCE(ts.stores_visited, 0) as stores_visited,
  COALESCE(ts.active_days, 0) as active_days_lifetime,
  COALESCE(ts.active_months, 0) as active_months_lifetime,
  
  -- Temporal preferences
  ts.first_transaction_date,
  ts.last_transaction_date,
  COALESCE(rb.days_since_last_purchase, 9999) as days_since_last_purchase,
  
  -- Time of day preferences (percentages)
  CASE 
    WHEN ts.total_transactions > 0 THEN ROUND(100.0 * ts.morning_transactions / ts.total_transactions, 2)
    ELSE 0
  END as morning_preference_pct,
  CASE 
    WHEN ts.total_transactions > 0 THEN ROUND(100.0 * ts.afternoon_transactions / ts.total_transactions, 2)
    ELSE 0
  END as afternoon_preference_pct,
  CASE 
    WHEN ts.total_transactions > 0 THEN ROUND(100.0 * ts.evening_transactions / ts.total_transactions, 2)
    ELSE 0
  END as evening_preference_pct,
  
  -- Day of week preferences
  CASE 
    WHEN ts.total_transactions > 0 THEN 
      CASE 
        WHEN ts.saturday_transactions >= ALL(ts.monday_transactions, ts.tuesday_transactions, ts.wednesday_transactions, ts.thursday_transactions, ts.friday_transactions, ts.sunday_transactions) THEN 'Saturday'
        WHEN ts.sunday_transactions >= ALL(ts.monday_transactions, ts.tuesday_transactions, ts.wednesday_transactions, ts.thursday_transactions, ts.friday_transactions, ts.saturday_transactions) THEN 'Sunday'
        WHEN ts.friday_transactions >= ALL(ts.monday_transactions, ts.tuesday_transactions, ts.wednesday_transactions, ts.thursday_transactions, ts.sunday_transactions, ts.saturday_transactions) THEN 'Friday'
        ELSE 'Weekday'
      END
    ELSE 'Unknown'
  END as preferred_shopping_day,
  
  -- Payment preferences
  COALESCE(ts.payment_methods_used, 0) as payment_methods_used,
  CASE 
    WHEN ts.total_transactions > 0 THEN 
      CASE 
        WHEN ts.credit_transactions >= ALL(ts.debit_transactions, ts.cash_transactions, ts.mobile_transactions) THEN 'Credit'
        WHEN ts.debit_transactions >= ALL(ts.credit_transactions, ts.cash_transactions, ts.mobile_transactions) THEN 'Debit'
        WHEN ts.cash_transactions >= ALL(ts.credit_transactions, ts.debit_transactions, ts.mobile_transactions) THEN 'Cash'
        WHEN ts.mobile_transactions >= ALL(ts.credit_transactions, ts.debit_transactions, ts.cash_transactions) THEN 'Mobile'
        ELSE 'Mixed'
      END
    ELSE 'Unknown'
  END as preferred_payment_method,
  
  -- Discount and promotion behavior
  COALESCE(ts.discounted_transactions, 0) as discounted_transactions,
  CASE 
    WHEN ts.total_transactions > 0 THEN ROUND(100.0 * ts.discounted_transactions / ts.total_transactions, 2)
    ELSE 0
  END as discount_usage_rate_pct,
  COALESCE(ts.total_discounts_received, 0) as total_discounts_received,
  
  -- Loyalty program engagement
  COALESCE(ts.total_points_earned, 0) as total_points_earned,
  COALESCE(ts.total_points_redeemed, 0) as total_points_redeemed,
  (COALESCE(ts.total_points_earned, 0) - COALESCE(ts.total_points_redeemed, 0)) as net_points_earned,
  CASE 
    WHEN ts.total_transactions > 0 THEN ROUND(100.0 * ts.point_earning_transactions / ts.total_transactions, 2)
    ELSE 0
  END as point_earning_rate_pct,
  
  -- Transaction size patterns
  CASE 
    WHEN ts.total_transactions > 0 THEN 
      CASE 
        WHEN ts.very_large_transactions >= ALL(ts.small_transactions, ts.medium_transactions, ts.large_transactions) THEN 'Very Large'
        WHEN ts.large_transactions >= ALL(ts.small_transactions, ts.medium_transactions, ts.very_large_transactions) THEN 'Large'
        WHEN ts.medium_transactions >= ALL(ts.small_transactions, ts.large_transactions, ts.very_large_transactions) THEN 'Medium'
        ELSE 'Small'
      END
    ELSE 'Unknown'
  END as preferred_transaction_size,
  
  -- Recent activity metrics
  COALESCE(rb.transactions_30d, 0) as transactions_30d,
  COALESCE(rb.spend_30d, 0) as spend_30d,
  COALESCE(rb.transactions_90d, 0) as transactions_90d,  
  COALESCE(rb.spend_90d, 0) as spend_90d,
  COALESCE(rb.transactions_365d, 0) as transactions_365d,
  COALESCE(rb.spend_365d, 0) as spend_365d,
  
  -- Activity frequency (transactions per active day)
  CASE 
    WHEN COALESCE(rb.active_days_30d, 0) > 0 THEN ROUND(COALESCE(rb.transactions_30d, 0) * 1.0 / rb.active_days_30d, 2)
    ELSE 0
  END as transaction_frequency_30d,
  CASE 
    WHEN COALESCE(rb.active_days_90d, 0) > 0 THEN ROUND(COALESCE(rb.transactions_90d, 0) * 1.0 / rb.active_days_90d, 2)  
    ELSE 0
  END as transaction_frequency_90d,
  
  -- Seasonality and trends
  COALESCE(ct.avg_winter_spend, 0) as avg_winter_spend,
  COALESCE(ct.avg_spring_spend, 0) as avg_spring_spend,
  COALESCE(ct.avg_summer_spend, 0) as avg_summer_spend,
  COALESCE(ct.avg_fall_spend, 0) as avg_fall_spend,
  COALESCE(ct.trend_direction, 'Unknown') as spending_trend,
  
  -- Customer lifetime metrics
  CASE 
    WHEN ts.first_transaction_date IS NOT NULL AND ts.last_transaction_date IS NOT NULL AND ts.active_days > 1 THEN
      ROUND(ts.lifetime_value / DATEDIFF(ts.last_transaction_date, ts.first_transaction_date) * 365, 2)
    ELSE 0
  END as annual_customer_value,
  
  CASE 
    WHEN ts.active_days > 0 THEN ROUND(ts.lifetime_value / ts.active_days, 2)
    ELSE 0
  END as value_per_active_day,
  
  -- Churn risk indicators
  CASE 
    WHEN COALESCE(rb.days_since_last_purchase, 9999) > 365 THEN 'High'
    WHEN COALESCE(rb.days_since_last_purchase, 9999) > 180 THEN 'Medium'
    WHEN COALESCE(rb.days_since_last_purchase, 9999) > 90 THEN 'Low'
    ELSE 'Active'
  END as churn_risk,
  
  -- Next best action recommendations
  CASE 
    WHEN cp.customer_segment = 'Champions' THEN 'Reward and retain with exclusive offers'
    WHEN cp.customer_segment = 'Loyal Customers' THEN 'Upsell premium products and services'
    WHEN cp.customer_segment = 'Potential Loyalists' THEN 'Offer loyalty program benefits'
    WHEN cp.customer_segment = 'New Customers' THEN 'Provide onboarding experience and education'
    WHEN cp.customer_segment = 'Promising' THEN 'Encourage repeat purchases with incentives'
    WHEN cp.customer_segment = 'Need Attention' THEN 'Re-engage with personalized campaigns'
    WHEN cp.customer_segment = 'About to Sleep' THEN 'Win-back campaigns with special offers'
    WHEN cp.customer_segment = 'Lost' THEN 'Aggressive win-back or sunset communications'
    ELSE 'Assess and categorize customer needs'
  END as recommended_action,
  
  -- Data quality and completeness
  cp.profile_completeness,
  CASE 
    WHEN cp.email_clean IS NOT NULL THEN true ELSE false
  END as has_email,
  CASE 
    WHEN cp.phone_standardized IS NOT NULL THEN true ELSE false
  END as has_phone,
  CASE 
    WHEN ts.total_transactions > 0 THEN true ELSE false
  END as has_transaction_history,
  
  -- Metadata and audit
  current_timestamp() as snapshot_date,
  current_timestamp() as processed_at,
  'gold_customer_360_v1' as model_version,
  ARRAY('silver_curated.customer_profiles_enriched', 'silver_curated.pos_transactions_cleansed') as source_tables

FROM silver_curated.customer_profiles_enriched cp
LEFT JOIN transaction_summary ts ON cp.customer_id = ts.customer_id  
LEFT JOIN recent_behavior rb ON cp.customer_id = rb.customer_id
LEFT JOIN customer_trends ct ON cp.customer_id = ct.customer_id
WHERE cp.customer_id IS NOT NULL