-- Gold Layer - Sales Fact Daily Aggregations  
-- Daily sales metrics with multi-dimensional analysis
-- Generated by Nexa Platform - DO NOT EDIT MANUALLY

CREATE OR REFRESH MATERIALIZED VIEW gold_analytics.sales_fact_daily (
  CONSTRAINT valid_date EXPECT (transaction_date IS NOT NULL) ON VIOLATION FAIL UPDATE,
  CONSTRAINT valid_metrics EXPECT (total_transactions >= 0 AND gross_revenue >= 0) ON VIOLATION FAIL UPDATE
)
PARTITIONED BY (transaction_year, transaction_month)
CLUSTER BY (transaction_date, store_id)
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true',
  'pipelines.reset.allowed' = 'false'
)
AS
WITH daily_store_metrics AS (
  -- Daily aggregations by store
  SELECT 
    transaction_date,
    store_id,
    
    -- Transaction counts
    COUNT(*) as total_transactions,
    COUNT(DISTINCT customer_id) as unique_customers,
    COUNT(CASE WHEN customer_id IS NOT NULL THEN 1 END) as member_transactions,
    COUNT(CASE WHEN customer_id IS NULL THEN 1 END) as guest_transactions,
    
    -- Revenue metrics
    SUM(total_amount) as gross_revenue,
    SUM(subtotal) as subtotal_revenue,
    SUM(tax_amount) as total_tax,
    SUM(discount_amount) as total_discounts,
    AVG(total_amount) as avg_transaction_value,
    MIN(total_amount) as min_transaction_value,
    MAX(total_amount) as max_transaction_value,
    STDDEV(total_amount) as transaction_value_stddev,
    
    -- Product metrics
    SUM(total_quantity) as total_items_sold,
    SUM(item_count) as total_line_items,
    AVG(total_quantity) as avg_items_per_transaction,
    AVG(item_count) as avg_line_items_per_transaction,
    
    -- Payment method breakdown
    COUNT(CASE WHEN payment_method_clean = 'CASH' THEN 1 END) as cash_transactions,
    COUNT(CASE WHEN payment_method_clean = 'CREDIT' THEN 1 END) as credit_transactions,
    COUNT(CASE WHEN payment_method_clean = 'DEBIT' THEN 1 END) as debit_transactions,
    COUNT(CASE WHEN payment_method_clean = 'MOBILE' THEN 1 END) as mobile_transactions,
    COUNT(CASE WHEN payment_method_clean = 'GIFT_CARD' THEN 1 END) as gift_card_transactions,
    
    SUM(CASE WHEN payment_method_clean = 'CASH' THEN total_amount ELSE 0 END) as cash_revenue,
    SUM(CASE WHEN payment_method_clean = 'CREDIT' THEN total_amount ELSE 0 END) as credit_revenue,
    SUM(CASE WHEN payment_method_clean = 'DEBIT' THEN total_amount ELSE 0 END) as debit_revenue,
    SUM(CASE WHEN payment_method_clean = 'MOBILE' THEN total_amount ELSE 0 END) as mobile_revenue,
    
    -- Time of day breakdown
    COUNT(CASE WHEN time_of_day = 'Morning' THEN 1 END) as morning_transactions,
    COUNT(CASE WHEN time_of_day = 'Afternoon' THEN 1 END) as afternoon_transactions,
    COUNT(CASE WHEN time_of_day = 'Evening' THEN 1 END) as evening_transactions,
    COUNT(CASE WHEN time_of_day = 'Night' THEN 1 END) as night_transactions,
    
    SUM(CASE WHEN time_of_day = 'Morning' THEN total_amount ELSE 0 END) as morning_revenue,
    SUM(CASE WHEN time_of_day = 'Afternoon' THEN total_amount ELSE 0 END) as afternoon_revenue,
    SUM(CASE WHEN time_of_day = 'Evening' THEN total_amount ELSE 0 END) as evening_revenue,
    SUM(CASE WHEN time_of_day = 'Night' THEN total_amount ELSE 0 END) as night_revenue,
    
    -- Transaction size breakdown
    COUNT(CASE WHEN transaction_size = 'Small' THEN 1 END) as small_transactions,
    COUNT(CASE WHEN transaction_size = 'Medium' THEN 1 END) as medium_transactions,
    COUNT(CASE WHEN transaction_size = 'Large' THEN 1 END) as large_transactions,
    COUNT(CASE WHEN transaction_size = 'Very Large' THEN 1 END) as very_large_transactions,
    
    -- Discount and promotion metrics
    COUNT(CASE WHEN discount_applied THEN 1 END) as discounted_transactions,
    COUNT(CASE WHEN promotion_count > 0 THEN 1 END) as promoted_transactions,
    SUM(CASE WHEN discount_applied THEN discount_amount ELSE 0 END) as promotional_discounts,
    
    -- Loyalty program metrics
    SUM(loyalty_points_earned) as total_points_earned,
    SUM(loyalty_points_redeemed) as total_points_redeemed,
    COUNT(CASE WHEN loyalty_points_earned > 0 THEN 1 END) as point_earning_transactions,
    COUNT(CASE WHEN loyalty_points_redeemed > 0 THEN 1 END) as point_redemption_transactions,
    
    -- Register performance
    COUNT(DISTINCT register_id) as active_registers,
    COUNT(DISTINCT cashier_id) as active_cashiers
    
  FROM silver_curated.pos_transactions_cleansed
  WHERE transaction_date IS NOT NULL
  GROUP BY transaction_date, store_id
),

daily_totals AS (
  -- Company-wide daily totals
  SELECT 
    transaction_date,
    
    -- Aggregate metrics across all stores
    SUM(total_transactions) as company_total_transactions,
    SUM(unique_customers) as company_unique_customers,
    SUM(gross_revenue) as company_gross_revenue,
    SUM(total_items_sold) as company_total_items_sold,
    COUNT(DISTINCT store_id) as active_stores,
    
    -- Company averages
    AVG(avg_transaction_value) as company_avg_transaction_value,
    AVG(avg_items_per_transaction) as company_avg_items_per_transaction
    
  FROM daily_store_metrics
  GROUP BY transaction_date
)

SELECT 
  -- Date dimensions
  dsm.transaction_date,
  YEAR(dsm.transaction_date) as transaction_year,
  MONTH(dsm.transaction_date) as transaction_month,
  DAYOFMONTH(dsm.transaction_date) as transaction_day,
  DAYOFWEEK(dsm.transaction_date) as day_of_week_num,
  CASE DAYOFWEEK(dsm.transaction_date)
    WHEN 1 THEN 'Sunday'
    WHEN 2 THEN 'Monday' 
    WHEN 3 THEN 'Tuesday'
    WHEN 4 THEN 'Wednesday'
    WHEN 5 THEN 'Thursday'
    WHEN 6 THEN 'Friday'
    WHEN 7 THEN 'Saturday'
  END as day_of_week_name,
  CASE 
    WHEN DAYOFWEEK(dsm.transaction_date) IN (1, 7) THEN 'Weekend'
    ELSE 'Weekday'
  END as day_type,
  WEEKOFYEAR(dsm.transaction_date) as week_of_year,
  QUARTER(dsm.transaction_date) as quarter,
  
  -- Store identifier
  dsm.store_id,
  
  -- Core transaction metrics
  dsm.total_transactions,
  dsm.unique_customers,
  dsm.member_transactions,
  dsm.guest_transactions,
  
  -- Customer penetration rates
  ROUND(100.0 * dsm.member_transactions / dsm.total_transactions, 2) as member_penetration_pct,
  ROUND(100.0 * dsm.guest_transactions / dsm.total_transactions, 2) as guest_penetration_pct,
  
  -- Revenue metrics
  dsm.gross_revenue,
  dsm.subtotal_revenue,
  dsm.total_tax,
  dsm.total_discounts,
  dsm.avg_transaction_value,
  dsm.min_transaction_value,
  dsm.max_transaction_value,
  dsm.transaction_value_stddev,
  
  -- Revenue composition
  ROUND(100.0 * dsm.total_tax / dsm.gross_revenue, 2) as tax_rate_pct,
  ROUND(100.0 * dsm.total_discounts / dsm.subtotal_revenue, 2) as discount_rate_pct,
  
  -- Product metrics
  dsm.total_items_sold,
  dsm.total_line_items,  
  dsm.avg_items_per_transaction,
  dsm.avg_line_items_per_transaction,
  
  -- Units per dollar (efficiency metric)
  CASE 
    WHEN dsm.gross_revenue > 0 THEN ROUND(dsm.total_items_sold / dsm.gross_revenue, 4)
    ELSE 0
  END as units_per_dollar,
  
  -- Payment method analysis
  dsm.cash_transactions,
  dsm.credit_transactions,
  dsm.debit_transactions,
  dsm.mobile_transactions,
  dsm.gift_card_transactions,
  
  -- Payment method percentages
  ROUND(100.0 * dsm.cash_transactions / dsm.total_transactions, 2) as cash_transaction_pct,
  ROUND(100.0 * dsm.credit_transactions / dsm.total_transactions, 2) as credit_transaction_pct,
  ROUND(100.0 * dsm.debit_transactions / dsm.total_transactions, 2) as debit_transaction_pct,
  ROUND(100.0 * dsm.mobile_transactions / dsm.total_transactions, 2) as mobile_transaction_pct,
  
  -- Payment method revenue mix
  dsm.cash_revenue,
  dsm.credit_revenue,
  dsm.debit_revenue,
  dsm.mobile_revenue,
  
  -- Time of day analysis
  dsm.morning_transactions,
  dsm.afternoon_transactions,
  dsm.evening_transactions,
  dsm.night_transactions,
  dsm.morning_revenue,
  dsm.afternoon_revenue,
  dsm.evening_revenue,
  dsm.night_revenue,
  
  -- Peak hour identification
  CASE 
    WHEN dsm.morning_revenue >= ALL(dsm.afternoon_revenue, dsm.evening_revenue, dsm.night_revenue) THEN 'Morning'
    WHEN dsm.afternoon_revenue >= ALL(dsm.morning_revenue, dsm.evening_revenue, dsm.night_revenue) THEN 'Afternoon'
    WHEN dsm.evening_revenue >= ALL(dsm.morning_revenue, dsm.afternoon_revenue, dsm.night_revenue) THEN 'Evening'
    ELSE 'Night'
  END as peak_revenue_period,
  
  -- Transaction size distribution
  dsm.small_transactions,
  dsm.medium_transactions,
  dsm.large_transactions,
  dsm.very_large_transactions,
  
  -- Transaction size percentages
  ROUND(100.0 * dsm.small_transactions / dsm.total_transactions, 2) as small_transaction_pct,
  ROUND(100.0 * dsm.medium_transactions / dsm.total_transactions, 2) as medium_transaction_pct,
  ROUND(100.0 * dsm.large_transactions / dsm.total_transactions, 2) as large_transaction_pct,
  ROUND(100.0 * dsm.very_large_transactions / dsm.total_transactions, 2) as very_large_transaction_pct,
  
  -- Promotional activity
  dsm.discounted_transactions,
  dsm.promoted_transactions,
  dsm.promotional_discounts,
  
  -- Promotional penetration
  ROUND(100.0 * dsm.discounted_transactions / dsm.total_transactions, 2) as discount_penetration_pct,
  ROUND(100.0 * dsm.promoted_transactions / dsm.total_transactions, 2) as promotion_penetration_pct,
  
  -- Loyalty program engagement
  dsm.total_points_earned,
  dsm.total_points_redeemed,
  dsm.point_earning_transactions,
  dsm.point_redemption_transactions,
  
  -- Loyalty engagement rates
  ROUND(100.0 * dsm.point_earning_transactions / dsm.total_transactions, 2) as point_earning_rate_pct,
  ROUND(100.0 * dsm.point_redemption_transactions / dsm.total_transactions, 2) as point_redemption_rate_pct,
  
  -- Operational metrics
  dsm.active_registers,
  dsm.active_cashiers,
  
  -- Productivity metrics
  CASE 
    WHEN dsm.active_registers > 0 THEN ROUND(dsm.total_transactions * 1.0 / dsm.active_registers, 2)
    ELSE 0
  END as transactions_per_register,
  CASE 
    WHEN dsm.active_cashiers > 0 THEN ROUND(dsm.gross_revenue / dsm.active_cashiers, 2)
    ELSE 0
  END as revenue_per_cashier,
  
  -- Company comparison metrics
  dt.company_total_transactions,
  dt.company_gross_revenue,
  dt.active_stores,
  
  -- Store performance vs company
  ROUND(100.0 * dsm.gross_revenue / dt.company_gross_revenue, 4) as store_revenue_share_pct,
  ROUND(100.0 * dsm.total_transactions / dt.company_total_transactions, 4) as store_transaction_share_pct,
  
  -- Performance indicators
  CASE 
    WHEN dsm.avg_transaction_value > dt.company_avg_transaction_value * 1.1 THEN 'Above Average'
    WHEN dsm.avg_transaction_value < dt.company_avg_transaction_value * 0.9 THEN 'Below Average'
    ELSE 'Average'
  END as atv_performance,
  
  CASE 
    WHEN dsm.avg_items_per_transaction > dt.company_avg_items_per_transaction * 1.1 THEN 'Above Average'
    WHEN dsm.avg_items_per_transaction < dt.company_avg_items_per_transaction * 0.9 THEN 'Below Average'
    ELSE 'Average'
  END as upt_performance,
  
  -- Data quality and audit
  CASE 
    WHEN dsm.total_transactions > 0 AND dsm.gross_revenue > 0 THEN 'Complete'
    ELSE 'Incomplete'
  END as data_quality_flag,
  
  -- Metadata
  current_timestamp() as processed_at,
  'gold_sales_fact_daily_v1' as model_version,
  ARRAY('silver_curated.pos_transactions_cleansed') as source_tables

FROM daily_store_metrics dsm
JOIN daily_totals dt ON dsm.transaction_date = dt.transaction_date
WHERE dsm.transaction_date IS NOT NULL
ORDER BY dsm.transaction_date DESC, dsm.store_id