-- Silver Layer - Customer Profiles Enriched
-- Enrich customer master data with calculated metrics and standardized attributes
-- Generated by Nexa Platform - DO NOT EDIT MANUALLY

CREATE OR REFRESH MATERIALIZED VIEW silver_curated.customer_profiles_enriched (
  CONSTRAINT valid_customer_id EXPECT (customer_id IS NOT NULL) ON VIOLATION FAIL UPDATE,
  CONSTRAINT valid_email_format EXPECT (email_clean RLIKE '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' OR email_clean IS NULL) ON VIOLATION QUARANTINE,
  CONSTRAINT valid_phone_format EXPECT (phone_standardized RLIKE '^\\+?[0-9]{10,15}$' OR phone_standardized IS NULL) ON VIOLATION QUARANTINE,
  CONSTRAINT valid_birth_date EXPECT (birth_date <= current_date() - INTERVAL 13 YEARS) ON VIOLATION QUARANTINE
)
PARTITIONED BY (customer_segment, registration_year)
CLUSTER BY (loyalty_tier, is_active)
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true',
  'pipelines.reset.allowed' = 'false'
)
AS
WITH customer_transaction_metrics AS (
  -- Calculate customer transaction history metrics from silver transactions
  SELECT 
    customer_id,
    COUNT(*) as total_transactions,
    SUM(total_amount) as lifetime_value,
    AVG(total_amount) as average_transaction_value,
    MAX(transaction_timestamp) as last_transaction_date,
    MIN(transaction_timestamp) as first_transaction_date,
    COUNT(DISTINCT transaction_date) as active_days,
    COUNT(DISTINCT store_id) as stores_visited,
    COUNT(DISTINCT payment_method_clean) as payment_methods_used,
    SUM(CASE WHEN discount_applied THEN 1 ELSE 0 END) as discounted_transactions,
    SUM(total_quantity) as total_items_purchased,
    AVG(total_quantity) as average_items_per_transaction,
    SUM(loyalty_points_earned) as total_points_earned,
    SUM(loyalty_points_redeemed) as total_points_redeemed
  FROM silver_curated.pos_transactions_cleansed
  WHERE customer_id IS NOT NULL
  GROUP BY customer_id
),

customer_recency_frequency AS (
  -- Calculate RFM (Recency, Frequency, Monetary) metrics
  SELECT 
    customer_id,
    DATEDIFF(current_date(), MAX(transaction_date)) as days_since_last_purchase,
    COUNT(*) as purchase_frequency_90d,
    SUM(total_amount) as monetary_value_90d,
    COUNT(DISTINCT transaction_date) as active_days_90d
  FROM silver_curated.pos_transactions_cleansed
  WHERE customer_id IS NOT NULL
    AND transaction_date >= current_date() - INTERVAL 90 DAYS
  GROUP BY customer_id
)

SELECT 
  -- Primary customer identifiers
  bc.customer_id,
  
  -- Personal information with standardization
  TRIM(UPPER(bc.first_name)) as first_name,
  TRIM(UPPER(bc.last_name)) as last_name,
  CONCAT(TRIM(UPPER(bc.first_name)), ' ', TRIM(UPPER(bc.last_name))) as full_name,
  
  -- Contact information standardization
  CASE 
    WHEN bc.email IS NOT NULL AND bc.email != '' AND bc.email NOT LIKE '%test%' 
    THEN LOWER(TRIM(bc.email))
    ELSE NULL
  END as email_clean,
  
  -- Phone number standardization (remove non-digits, add country code)
  CASE 
    WHEN bc.phone IS NOT NULL AND bc.phone != '' THEN
      CASE 
        WHEN REGEXP_REPLACE(bc.phone, '[^0-9]', '') RLIKE '^1[0-9]{10}$' 
        THEN CONCAT('+', REGEXP_REPLACE(bc.phone, '[^0-9]', ''))
        WHEN REGEXP_REPLACE(bc.phone, '[^0-9]', '') RLIKE '^[0-9]{10}$'
        THEN CONCAT('+1', REGEXP_REPLACE(bc.phone, '[^0-9]', ''))
        ELSE REGEXP_REPLACE(bc.phone, '[^0-9]', '')
      END
    ELSE NULL
  END as phone_standardized,
  
  -- Address information with parsing
  TRIM(bc.address_line1) as address_line1,
  TRIM(bc.address_line2) as address_line2,
  TRIM(UPPER(bc.city)) as city,
  TRIM(UPPER(bc.state)) as state_province,
  TRIM(bc.postal_code) as postal_code,
  TRIM(UPPER(bc.country)) as country,
  
  -- Geographic standardization
  CASE 
    WHEN UPPER(bc.country) IN ('US', 'USA', 'UNITED STATES') THEN 'US'
    WHEN UPPER(bc.country) IN ('CA', 'CAN', 'CANADA') THEN 'CA'
    WHEN UPPER(bc.country) IN ('UK', 'GB', 'UNITED KINGDOM') THEN 'GB'
    ELSE UPPER(bc.country)
  END as country_code,
  
  -- Demographic information
  bc.birth_date,
  CASE 
    WHEN bc.birth_date IS NOT NULL THEN 
      FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25)
    ELSE NULL
  END as age_years,
  
  -- Age group classification
  CASE 
    WHEN bc.birth_date IS NULL THEN 'Unknown'
    WHEN FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25) < 18 THEN 'Under 18'
    WHEN FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25) < 25 THEN '18-24'
    WHEN FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25) < 35 THEN '25-34'
    WHEN FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25) < 45 THEN '35-44'
    WHEN FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25) < 55 THEN '45-54'
    WHEN FLOOR(DATEDIFF(current_date(), bc.birth_date) / 365.25) < 65 THEN '55-64'
    ELSE '65+'
  END as age_group,
  
  CASE 
    WHEN UPPER(bc.gender) IN ('M', 'MALE') THEN 'M'
    WHEN UPPER(bc.gender) IN ('F', 'FEMALE') THEN 'F'
    WHEN UPPER(bc.gender) IN ('O', 'OTHER', 'NON-BINARY') THEN 'O'
    ELSE 'Unknown'
  END as gender_standardized,
  
  -- Account information
  bc.registration_date,
  YEAR(bc.registration_date) as registration_year,
  DATEDIFF(current_date(), bc.registration_date) as customer_tenure_days,
  
  -- Customer status
  COALESCE(bc.is_active, true) as is_active,
  bc.is_email_verified,
  bc.is_phone_verified,
  bc.marketing_opt_in,
  bc.sms_opt_in,
  
  -- Loyalty program information  
  bc.loyalty_program_id,
  COALESCE(UPPER(bc.loyalty_tier), 'BRONZE') as loyalty_tier,
  COALESCE(bc.loyalty_points_balance, 0) as loyalty_points_balance,
  
  -- Customer preferences (JSON flattening)
  CASE 
    WHEN bc.preferences IS NOT NULL AND bc.preferences != '' THEN bc.preferences
    ELSE NULL
  END as preferences_json,
  
  -- Extract specific preferences
  CASE 
    WHEN bc.preferences IS NOT NULL AND bc.preferences != '' THEN
      GET_JSON_OBJECT(bc.preferences, '$.communication_channel')
    ELSE 'email'
  END as preferred_communication_channel,
  
  CASE 
    WHEN bc.preferences IS NOT NULL AND bc.preferences != '' THEN
      GET_JSON_OBJECT(bc.preferences, '$.shopping_categories')
    ELSE NULL
  END as preferred_categories_json,
  
  -- Transaction-based metrics (from CTE)
  COALESCE(ctm.total_transactions, 0) as total_transactions,
  COALESCE(ctm.lifetime_value, 0) as lifetime_value,
  COALESCE(ctm.average_transaction_value, 0) as average_transaction_value,
  ctm.last_transaction_date,
  ctm.first_transaction_date,
  COALESCE(ctm.active_days, 0) as active_days,
  COALESCE(ctm.stores_visited, 0) as stores_visited,
  COALESCE(ctm.payment_methods_used, 0) as payment_methods_used,
  COALESCE(ctm.total_items_purchased, 0) as total_items_purchased,
  COALESCE(ctm.average_items_per_transaction, 0) as average_items_per_transaction,
  
  -- Recent activity metrics (from CTE)
  COALESCE(crf.days_since_last_purchase, 9999) as days_since_last_purchase,
  COALESCE(crf.purchase_frequency_90d, 0) as purchase_frequency_90d,
  COALESCE(crf.monetary_value_90d, 0) as monetary_value_90d,
  COALESCE(crf.active_days_90d, 0) as active_days_90d,
  
  -- Customer segmentation based on RFM
  CASE 
    WHEN COALESCE(crf.days_since_last_purchase, 9999) <= 30 AND COALESCE(crf.purchase_frequency_90d, 0) >= 5 AND COALESCE(crf.monetary_value_90d, 0) >= 500 THEN 'Champions'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) <= 30 AND COALESCE(crf.purchase_frequency_90d, 0) >= 3 AND COALESCE(crf.monetary_value_90d, 0) >= 200 THEN 'Loyal Customers'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) <= 60 AND COALESCE(crf.monetary_value_90d, 0) >= 300 THEN 'Potential Loyalists'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) <= 30 AND COALESCE(crf.purchase_frequency_90d, 0) = 1 AND COALESCE(crf.monetary_value_90d, 0) >= 100 THEN 'New Customers'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) <= 60 AND COALESCE(crf.purchase_frequency_90d, 0) >= 2 THEN 'Promising'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) BETWEEN 61 AND 120 THEN 'Need Attention'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) BETWEEN 121 AND 365 THEN 'About to Sleep'
    WHEN COALESCE(crf.days_since_last_purchase, 9999) > 365 OR ctm.total_transactions IS NULL THEN 'Lost'
    ELSE 'Others'
  END as customer_segment,
  
  -- Customer value tier
  CASE 
    WHEN COALESCE(ctm.lifetime_value, 0) >= 5000 THEN 'High Value'
    WHEN COALESCE(ctm.lifetime_value, 0) >= 1000 THEN 'Medium Value'  
    WHEN COALESCE(ctm.lifetime_value, 0) >= 100 THEN 'Low Value'
    ELSE 'New/No Purchase'
  END as value_tier,
  
  -- Engagement score (0-100)
  LEAST(100, 
    CASE 
      WHEN ctm.total_transactions IS NULL THEN 0
      ELSE 
        (CASE WHEN COALESCE(crf.days_since_last_purchase, 9999) <= 30 THEN 30 ELSE GREATEST(0, 30 - COALESCE(crf.days_since_last_purchase, 9999) / 10) END) +
        (LEAST(25, COALESCE(crf.purchase_frequency_90d, 0) * 5)) +
        (LEAST(25, COALESCE(crf.monetary_value_90d, 0) / 20)) +
        (CASE WHEN bc.marketing_opt_in THEN 10 ELSE 0 END) +
        (CASE WHEN bc.is_email_verified THEN 5 ELSE 0 END) +
        (CASE WHEN bc.is_phone_verified THEN 5 ELSE 0 END)
    END
  ) as engagement_score,
  
  -- Data quality indicators
  CASE 
    WHEN bc.email IS NOT NULL AND bc.phone IS NOT NULL AND bc.birth_date IS NOT NULL 
    THEN 'Complete'
    WHEN bc.email IS NOT NULL OR bc.phone IS NOT NULL 
    THEN 'Partial'
    ELSE 'Minimal'
  END as profile_completeness,
  
  -- Source and audit fields
  bc.source_system,
  bc.created_date as profile_created_date,
  bc.modified_date as profile_modified_date,
  bc.file_path as source_file_path,
  bc.ingested_at as source_ingested_at,
  current_timestamp() as processed_at,
  
  -- Data lineage
  'bronze_batch.crm_customers' as source_table,
  'silver_customer_profiles_v1' as transformation_version

FROM bronze_batch.crm_customers bc
LEFT JOIN customer_transaction_metrics ctm ON bc.customer_id = ctm.customer_id
LEFT JOIN customer_recency_frequency crf ON bc.customer_id = crf.customer_id
WHERE 
  -- Data quality filters
  bc.customer_id IS NOT NULL
  -- Exclude test customers
  AND bc.customer_id NOT LIKE '%TEST%'
  AND COALESCE(bc.email, '') NOT LIKE '%test%'
  AND COALESCE(bc.email, '') NOT LIKE '%example%'