-- Silver Layer - POS Transactions Cleansed
-- Transform raw POS transaction data with JSON flattening and data quality improvements
-- Generated by Nexa Platform - DO NOT EDIT MANUALLY

CREATE OR REFRESH STREAMING TABLE silver_curated.pos_transactions_cleansed (
  CONSTRAINT valid_transaction_id EXPECT (transaction_id IS NOT NULL) ON VIOLATION FAIL UPDATE,
  CONSTRAINT positive_amounts EXPECT (total_amount > 0 AND subtotal > 0) ON VIOLATION DROP,
  CONSTRAINT valid_store_format EXPECT (store_id RLIKE '^STORE_[0-9]{4}$') ON VIOLATION QUARANTINE,
  CONSTRAINT payment_method_valid EXPECT (payment_method_clean IN ('CASH', 'CREDIT', 'DEBIT', 'MOBILE', 'GIFT_CARD', 'CHECK')) ON VIOLATION QUARANTINE,
  CONSTRAINT amounts_balance EXPECT (ABS(total_amount - calculated_total) < 0.01) ON VIOLATION QUARANTINE
)
PARTITIONED BY (transaction_date, store_id)
CLUSTER BY (customer_id, payment_method_clean)
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.optimizeWrite' = 'true',
  'delta.autoOptimize.autoCompact' = 'true',
  'pipelines.reset.allowed' = 'false'
)
AS
SELECT 
  -- Primary transaction identifiers
  transaction_id,
  store_id,
  register_id,
  cashier_id,
  CASE 
    WHEN customer_id = '' OR customer_id = 'NULL' THEN NULL
    ELSE customer_id 
  END as customer_id,
  
  -- Timestamp fields with timezone normalization
  transaction_timestamp,
  CAST(transaction_timestamp AS DATE) as transaction_date,
  DATE_FORMAT(transaction_timestamp, 'yyyy-MM') as transaction_month,
  DATE_FORMAT(transaction_timestamp, 'yyyy') as transaction_year,
  HOUR(transaction_timestamp) as transaction_hour,
  CASE 
    WHEN HOUR(transaction_timestamp) BETWEEN 6 AND 11 THEN 'Morning'
    WHEN HOUR(transaction_timestamp) BETWEEN 12 AND 17 THEN 'Afternoon'  
    WHEN HOUR(transaction_timestamp) BETWEEN 18 AND 21 THEN 'Evening'
    ELSE 'Night'
  END as time_of_day,
  DAYOFWEEK(transaction_timestamp) as day_of_week,
  CASE DAYOFWEEK(transaction_timestamp)
    WHEN 1 THEN 'Sunday'
    WHEN 2 THEN 'Monday'
    WHEN 3 THEN 'Tuesday'
    WHEN 4 THEN 'Wednesday'
    WHEN 5 THEN 'Thursday'
    WHEN 6 THEN 'Friday'
    WHEN 7 THEN 'Saturday'
  END as day_name,
  
  -- Financial amounts with validation
  CAST(subtotal AS DECIMAL(15,2)) as subtotal,
  CAST(COALESCE(tax_amount, 0) AS DECIMAL(10,2)) as tax_amount,
  CAST(COALESCE(discount_amount, 0) AS DECIMAL(10,2)) as discount_amount,
  CAST(total_amount AS DECIMAL(15,2)) as total_amount,
  
  -- Calculated total for validation
  CAST((subtotal + COALESCE(tax_amount, 0) - COALESCE(discount_amount, 0)) AS DECIMAL(15,2)) as calculated_total,
  
  -- Tax rate calculation
  CASE 
    WHEN subtotal > 0 THEN CAST((COALESCE(tax_amount, 0) / subtotal) AS DECIMAL(8,4))
    ELSE 0
  END as tax_rate,
  
  -- Discount percentage
  CASE 
    WHEN subtotal > 0 THEN CAST((COALESCE(discount_amount, 0) / subtotal) AS DECIMAL(8,4))
    ELSE 0
  END as discount_percentage,
  
  -- Payment information cleaned
  UPPER(TRIM(payment_method)) as payment_method_clean,
  CASE 
    WHEN payment_details IS NULL OR payment_details = '' THEN NULL
    ELSE payment_details 
  END as payment_details_json,
  
  -- Receipt and reference data
  receipt_number,
  
  -- JSON Flattening - Items Array Processing
  -- Extract individual items from JSON array and create metrics
  CASE 
    WHEN items IS NOT NULL AND items != '' THEN
      SIZE(FROM_JSON(items, 'array<struct<product_id:string,quantity:int,unit_price:decimal(10,2),line_total:decimal(10,2)>>'))
    ELSE 0
  END as item_count,
  
  -- Items JSON for downstream processing
  CASE 
    WHEN items IS NOT NULL AND items != '' AND items != '[]' THEN items
    ELSE NULL
  END as items_json,
  
  -- Flatten specific item metrics
  CASE 
    WHEN items IS NOT NULL AND items != '' THEN
      AGGREGATE(
        FROM_JSON(items, 'array<struct<quantity:int>>'),
        0,
        (acc, x) -> acc + COALESCE(x.quantity, 0)
      )
    ELSE 0
  END as total_quantity,
  
  -- Average item price
  CASE 
    WHEN items IS NOT NULL AND items != '' AND SIZE(FROM_JSON(items, 'array<struct<unit_price:decimal(10,2)>>')) > 0 THEN
      CAST(
        AGGREGATE(
          FROM_JSON(items, 'array<struct<unit_price:decimal(10,2)>>'),
          0.0,
          (acc, x) -> acc + COALESCE(x.unit_price, 0)
        ) / SIZE(FROM_JSON(items, 'array<struct<unit_price:decimal(10,2)>>')) AS DECIMAL(10,2)
      )
    ELSE 0
  END as average_item_price,
  
  -- Promotion and loyalty data with JSON flattening
  CASE 
    WHEN promotion_codes IS NOT NULL AND promotion_codes != '' AND promotion_codes != '[]' THEN 
      promotion_codes
    ELSE NULL
  END as promotion_codes_json,
  
  -- Extract promotion count
  CASE 
    WHEN promotion_codes IS NOT NULL AND promotion_codes != '' AND promotion_codes != '[]' THEN
      SIZE(FROM_JSON(promotion_codes, 'array<string>'))
    ELSE 0
  END as promotion_count,
  
  -- Loyalty points processing
  COALESCE(loyalty_points_earned, 0) as loyalty_points_earned,
  COALESCE(loyalty_points_redeemed, 0) as loyalty_points_redeemed,
  (COALESCE(loyalty_points_earned, 0) - COALESCE(loyalty_points_redeemed, 0)) as net_loyalty_points,
  
  -- Customer classification
  CASE 
    WHEN customer_id IS NOT NULL THEN 'Member'
    ELSE 'Guest'
  END as customer_type,
  
  -- Transaction size classification  
  CASE 
    WHEN total_amount < 10 THEN 'Small'
    WHEN total_amount < 50 THEN 'Medium'
    WHEN total_amount < 200 THEN 'Large'
    ELSE 'Very Large'
  END as transaction_size,
  
  -- Discount applied flag
  CASE 
    WHEN COALESCE(discount_amount, 0) > 0 OR 
         (promotion_codes IS NOT NULL AND promotion_codes != '' AND promotion_codes != '[]') OR
         COALESCE(loyalty_points_redeemed, 0) > 0 
    THEN true
    ELSE false
  END as discount_applied,
  
  -- Data quality flags
  CASE 
    WHEN ABS(total_amount - (subtotal + COALESCE(tax_amount, 0) - COALESCE(discount_amount, 0))) >= 0.01 
    THEN true 
    ELSE false 
  END as amount_mismatch_flag,
  
  CASE 
    WHEN items IS NULL OR items = '' OR items = '[]' 
    THEN true 
    ELSE false 
  END as missing_items_flag,
  
  -- Source tracking
  kafka_partition,
  kafka_offset,
  kafka_timestamp,
  ingested_at,
  current_timestamp() as processed_at,
  
  -- Data lineage
  'bronze_streaming.pos_transactions' as source_table,
  'silver_pos_transactions_v1' as transformation_version
  
FROM STREAM(bronze_streaming.pos_transactions)
WHERE 
  -- Data quality filters
  transaction_id IS NOT NULL
  AND store_id IS NOT NULL  
  AND transaction_timestamp IS NOT NULL
  AND total_amount > 0
  -- Filter out test transactions
  AND store_id NOT LIKE '%TEST%'
  AND cashier_id NOT IN ('TEST_USER', 'TRAINING_USER')
  -- Time window filter - only process recent data
  AND transaction_timestamp > current_timestamp() - INTERVAL 7 DAYS