#
# Generated by [YOUR PRODUCT NAME] - Licensed Software
# Copyright (c) [YEAR] [YOUR COMPANY NAME]. All rights reserved.
# 
# License Required: Continued use requires active [PRODUCT] license.
# Upon license expiration, all usage rights terminate immediately.
# 
# Permitted: Modify for business use during active license period.
# Prohibited: Use after license expiration, redistribution, resale.
# 
# Generated: [DATE] | Version: [VERSION] | Support: [EMAIL]
#

# Databricks notebook source
# MAGIC %md
# MAGIC # Bronze Layer - Kafka POS Transactions Processing
# MAGIC 
# MAGIC **Purpose**: Real-time ingestion and processing of POS transactions from Kafka topic
# MAGIC 
# MAGIC **Source**: Kafka topic `pos-transactions-v1`  
# MAGIC **Target**: `bronze_streaming.pos_transactions`
# MAGIC **Processing**: JSON parsing, schema validation, data quality checks
# MAGIC 
# MAGIC Generated by Nexa Platform - DO NOT EDIT MANUALLY

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration and Setup

# COMMAND ----------

import dlt
from pyspark.sql import functions as F
from pyspark.sql.types import *
import json
import uuid
from datetime import datetime

# Kafka configuration - these should be set as pipeline configuration
KAFKA_BOOTSTRAP_SERVERS = spark.conf.get("pipelines.kafka.bootstrap.servers", "kafka-cluster.megamart.internal:9092")
KAFKA_TOPIC = "pos-transactions-v1"
CHECKPOINT_LOCATION = "s3://megamart-data-lake-prod/checkpoints/bronze_pos_transactions_kafka/"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Schema Definition

# COMMAND ----------

# Define the expected schema for POS transaction messages
pos_transaction_schema = StructType([
    StructField("transaction_id", StringType(), False),
    StructField("store_id", StringType(), False),
    StructField("register_id", StringType(), False),
    StructField("cashier_id", StringType(), True),
    StructField("customer_id", StringType(), True),
    StructField("transaction_timestamp", TimestampType(), False),
    StructField("items", StringType(), False),  # JSON string
    StructField("subtotal", DecimalType(15,2), False),
    StructField("tax_amount", DecimalType(10,2), False),
    StructField("discount_amount", DecimalType(10,2), True),
    StructField("total_amount", DecimalType(15,2), False),
    StructField("payment_method", StringType(), False),
    StructField("payment_details", StringType(), True),
    StructField("receipt_number", StringType(), True),
    StructField("promotion_codes", StringType(), True),  # JSON string
    StructField("loyalty_points_earned", IntegerType(), True),
    StructField("loyalty_points_redeemed", IntegerType(), True)
])

# COMMAND ----------

# MAGIC %md
# MAGIC ## Data Quality Functions

# COMMAND ----------

def validate_transaction_data(df):
    """Apply data quality validations to transaction data"""
    
    # Add data quality flags
    df = df.withColumn(
        "dq_transaction_id_valid",
        F.when(
            (F.col("transaction_id").isNotNull()) & 
            (F.length("transaction_id") >= 10), 
            True
        ).otherwise(False)
    )
    
    df = df.withColumn(
        "dq_amounts_valid",
        F.when(
            (F.col("total_amount") > 0) & 
            (F.col("subtotal") > 0) &
            (F.abs(F.col("total_amount") - (
                F.col("subtotal") + 
                F.coalesce(F.col("tax_amount"), F.lit(0)) - 
                F.coalesce(F.col("discount_amount"), F.lit(0))
            )) < 0.01),
            True
        ).otherwise(False)
    )
    
    df = df.withColumn(
        "dq_store_format_valid",
        F.when(F.col("store_id").rlike("^STORE_[0-9]{4}$"), True).otherwise(False)
    )
    
    df = df.withColumn(
        "dq_timestamp_valid",
        F.when(
            (F.col("transaction_timestamp").isNotNull()) &
            (F.col("transaction_timestamp") > F.current_timestamp() - F.expr("INTERVAL 1 DAY")) &
            (F.col("transaction_timestamp") <= F.current_timestamp()),
            True
        ).otherwise(False)
    )
    
    df = df.withColumn(
        "dq_items_valid",
        F.when(
            (F.col("items").isNotNull()) & 
            (F.length("items") > 0) & 
            (F.col("items") != "[]"),
            True
        ).otherwise(False)
    )
    
    # Overall data quality score (percentage of checks passed)
    df = df.withColumn(
        "data_quality_score",
        (
            F.col("dq_transaction_id_valid").cast("int") +
            F.col("dq_amounts_valid").cast("int") +
            F.col("dq_store_format_valid").cast("int") +
            F.col("dq_timestamp_valid").cast("int") +
            F.col("dq_items_valid").cast("int")
        ) / 5.0 * 100
    )
    
    return df

def parse_kafka_message(df):
    """Parse Kafka message structure and extract transaction data"""
    
    # Parse the Kafka value as JSON
    df = df.withColumn("value_json", F.from_json(F.col("value").cast("string"), pos_transaction_schema))
    
    # Extract all fields from the nested JSON structure
    df = df.select(
        # Kafka metadata
        F.col("partition").alias("kafka_partition"),
        F.col("offset").alias("kafka_offset"),
        F.col("timestamp").alias("kafka_timestamp"),
        F.col("timestampType").alias("kafka_timestamp_type"),
        
        # Transaction data
        F.col("value_json.transaction_id").alias("transaction_id"),
        F.col("value_json.store_id").alias("store_id"),
        F.col("value_json.register_id").alias("register_id"),
        F.col("value_json.cashier_id").alias("cashier_id"),
        F.col("value_json.customer_id").alias("customer_id"),
        F.col("value_json.transaction_timestamp").alias("transaction_timestamp"),
        F.col("value_json.items").alias("items"),
        F.col("value_json.subtotal").alias("subtotal"),
        F.col("value_json.tax_amount").alias("tax_amount"),
        F.col("value_json.discount_amount").alias("discount_amount"),
        F.col("value_json.total_amount").alias("total_amount"),
        F.col("value_json.payment_method").alias("payment_method"),
        F.col("value_json.payment_details").alias("payment_details"),
        F.col("value_json.receipt_number").alias("receipt_number"),
        F.col("value_json.promotion_codes").alias("promotion_codes"),
        F.col("value_json.loyalty_points_earned").alias("loyalty_points_earned"),
        F.col("value_json.loyalty_points_redeemed").alias("loyalty_points_redeemed")
    )
    
    # Add derived fields
    df = df.withColumn(
        "transaction_date",
        F.to_date("transaction_timestamp")
    )
    
    df = df.withColumn(
        "ingested_at",
        F.current_timestamp()
    )
    
    return df

def enrich_transaction_data(df):
    """Add business logic and enrichments to transaction data"""
    
    # Clean and standardize payment method
    df = df.withColumn(
        "payment_method_clean",
        F.upper(F.trim(F.col("payment_method")))
    )
    
    # Extract item count from JSON
    df = df.withColumn(
        "item_count",
        F.when(
            (F.col("items").isNotNull()) & (F.col("items") != "") & (F.col("items") != "[]"),
            F.size(F.from_json(F.col("items"), "array<struct<product_id:string,quantity:int>>"))
        ).otherwise(0)
    )
    
    # Extract total quantity from JSON items
    df = df.withColumn(
        "total_quantity",
        F.when(
            (F.col("items").isNotNull()) & (F.col("items") != "") & (F.col("items") != "[]"),
            F.aggregate(
                F.from_json(F.col("items"), "array<struct<quantity:int>>"),
                F.lit(0),
                lambda acc, x: acc + F.coalesce(x.quantity, F.lit(0))
            )
        ).otherwise(0)
    )
    
    # Extract promotion count
    df = df.withColumn(
        "promotion_count",
        F.when(
            (F.col("promotion_codes").isNotNull()) & 
            (F.col("promotion_codes") != "") & 
            (F.col("promotion_codes") != "[]"),
            F.size(F.from_json(F.col("promotion_codes"), "array<string>"))
        ).otherwise(0)
    )
    
    # Calculate net loyalty points
    df = df.withColumn(
        "net_loyalty_points",
        F.coalesce(F.col("loyalty_points_earned"), F.lit(0)) - 
        F.coalesce(F.col("loyalty_points_redeemed"), F.lit(0))
    )
    
    # Determine if discount was applied
    df = df.withColumn(
        "discount_applied",
        F.when(
            (F.coalesce(F.col("discount_amount"), F.lit(0)) > 0) |
            (F.col("promotion_count") > 0) |
            (F.coalesce(F.col("loyalty_points_redeemed"), F.lit(0)) > 0),
            True
        ).otherwise(False)
    )
    
    # Customer type classification
    df = df.withColumn(
        "customer_type",
        F.when(F.col("customer_id").isNotNull(), "Member").otherwise("Guest")
    )
    
    # Transaction size classification
    df = df.withColumn(
        "transaction_size",
        F.when(F.col("total_amount") < 10, "Small")
         .when(F.col("total_amount") < 50, "Medium")
         .when(F.col("total_amount") < 200, "Large")
         .otherwise("Very Large")
    )
    
    return df

# COMMAND ----------

# MAGIC %md
# MAGIC ## DLT Table Definition

# COMMAND ----------

@dlt.table(
    name="pos_transactions",
    comment="Real-time POS transactions from Kafka with data quality validations",
    table_properties={
        "delta.enableChangeDataFeed": "true",
        "delta.autoOptimize.optimizeWrite": "true",
        "delta.autoOptimize.autoCompact": "true",
        "pipelines.reset.allowed": "false"
    },
    partition_cols=["transaction_date"],
    path="s3://megamart-data-lake-prod/bronze/streaming/pos_transactions/"
)
@dlt.expect_all({
    "valid_transaction_id": "transaction_id IS NOT NULL AND length(transaction_id) >= 10",
    "positive_amounts": "total_amount > 0 AND subtotal > 0",
    "valid_timestamp": "transaction_timestamp IS NOT NULL",
    "valid_store_format": "store_id RLIKE '^STORE_[0-9]{4}$'",
    "items_present": "items IS NOT NULL AND length(items) > 0",
    "amounts_balance": "ABS(total_amount - (subtotal + COALESCE(tax_amount, 0) - COALESCE(discount_amount, 0))) < 0.01"
})
def bronze_pos_transactions():
    """
    Bronze layer streaming table for POS transactions from Kafka.
    
    Applies JSON parsing, data quality checks, and basic enrichments.
    """
    
    # Read from Kafka topic
    kafka_df = (
        spark.readStream
        .format("kafka")
        .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS)
        .option("subscribe", KAFKA_TOPIC)
        .option("startingOffsets", "latest")
        .option("maxOffsetsPerTrigger", 10000)
        .option("kafka.security.protocol", "SASL_SSL")
        .option("kafka.sasl.mechanism", "PLAIN")
        .option("failOnDataLoss", "false")
        .load()
    )
    
    # Parse Kafka messages
    parsed_df = parse_kafka_message(kafka_df)
    
    # Apply data quality validations
    validated_df = validate_transaction_data(parsed_df)
    
    # Add business enrichments
    enriched_df = enrich_transaction_data(validated_df)
    
    # Filter out messages that fail critical validations
    filtered_df = enriched_df.filter(
        (F.col("dq_transaction_id_valid") == True) &
        (F.col("dq_amounts_valid") == True) &
        (F.col("dq_timestamp_valid") == True) &
        (F.col("dq_items_valid") == True) &
        # Exclude test transactions
        (~F.col("store_id").like("%TEST%")) &
        (~F.col("cashier_id").isin(["TEST_USER", "TRAINING_USER"]))
    )
    
    return filtered_df

# COMMAND ----------

# MAGIC %md
# MAGIC ## Data Quality Monitoring

# COMMAND ----------

@dlt.table(
    name="pos_transactions_quality_metrics",
    comment="Data quality metrics for POS transactions stream",
    table_properties={
        "delta.enableChangeDataFeed": "true"
    }
)
def pos_transactions_quality_metrics():
    """
    Data quality monitoring table for POS transactions.
    
    Tracks validation failures and data quality trends over time.
    """
    
    base_df = dlt.read_stream("pos_transactions")
    
    # Aggregate quality metrics by time windows
    quality_df = (
        base_df
        .withWatermark("kafka_timestamp", "5 minutes")
        .groupBy(
            F.window("kafka_timestamp", "5 minutes").alias("time_window"),
            "store_id"
        )
        .agg(
            F.count("*").alias("total_records"),
            F.sum(F.col("dq_transaction_id_valid").cast("int")).alias("valid_transaction_ids"),
            F.sum(F.col("dq_amounts_valid").cast("int")).alias("valid_amounts"),
            F.sum(F.col("dq_store_format_valid").cast("int")).alias("valid_store_formats"),
            F.sum(F.col("dq_timestamp_valid").cast("int")).alias("valid_timestamps"),
            F.sum(F.col("dq_items_valid").cast("int")).alias("valid_items"),
            F.avg("data_quality_score").alias("avg_quality_score"),
            F.min("data_quality_score").alias("min_quality_score"),
            F.max("data_quality_score").alias("max_quality_score"),
            F.sum("total_amount").alias("total_revenue"),
            F.count("transaction_id").alias("processed_transactions"),
            F.current_timestamp().alias("processed_at")
        )
    )
    
    # Calculate quality rates
    quality_df = quality_df.withColumn(
        "transaction_id_quality_rate",
        F.col("valid_transaction_ids") / F.col("total_records") * 100
    ).withColumn(
        "amounts_quality_rate", 
        F.col("valid_amounts") / F.col("total_records") * 100
    ).withColumn(
        "overall_quality_rate",
        (F.col("valid_transaction_ids") + F.col("valid_amounts") + 
         F.col("valid_store_formats") + F.col("valid_timestamps") + F.col("valid_items")) / 
        (F.col("total_records") * 5) * 100
    )
    
    return quality_df

# COMMAND ----------

# MAGIC %md
# MAGIC ## Error Handling and Dead Letter Queue

# COMMAND ----------

@dlt.table(
    name="pos_transactions_errors",
    comment="Failed POS transactions for investigation and reprocessing",
    table_properties={
        "delta.enableChangeDataFeed": "true"
    }
)
def pos_transactions_errors():
    """
    Dead letter queue for POS transactions that fail critical validations.
    
    Captures failed records for investigation and potential reprocessing.
    """
    
    # Read the raw stream again for error capture
    kafka_df = (
        spark.readStream
        .format("kafka")
        .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS)
        .option("subscribe", KAFKA_TOPIC)
        .option("startingOffsets", "latest")
        .option("maxOffsetsPerTrigger", 10000)
        .option("failOnDataLoss", "false")
        .load()
    )
    
    # Parse and validate
    parsed_df = parse_kafka_message(kafka_df)
    validated_df = validate_transaction_data(parsed_df)
    
    # Capture only failed records
    error_df = validated_df.filter(
        (F.col("dq_transaction_id_valid") == False) |
        (F.col("dq_amounts_valid") == False) |
        (F.col("dq_timestamp_valid") == False) |
        (F.col("dq_items_valid") == False) |
        # Also capture test transactions
        (F.col("store_id").like("%TEST%")) |
        (F.col("cashier_id").isin(["TEST_USER", "TRAINING_USER"]))
    )
    
    # Add error categorization
    error_df = error_df.withColumn(
        "error_category",
        F.when(~F.col("dq_transaction_id_valid"), "INVALID_TRANSACTION_ID")
         .when(~F.col("dq_amounts_valid"), "INVALID_AMOUNTS")  
         .when(~F.col("dq_timestamp_valid"), "INVALID_TIMESTAMP")
         .when(~F.col("dq_items_valid"), "INVALID_ITEMS")
         .when(F.col("store_id").like("%TEST%"), "TEST_TRANSACTION")
         .otherwise("OTHER_ERROR")
    )
    
    # Add error details
    error_df = error_df.withColumn(
        "error_details",
        F.struct(
            F.col("dq_transaction_id_valid").alias("transaction_id_valid"),
            F.col("dq_amounts_valid").alias("amounts_valid"),
            F.col("dq_store_format_valid").alias("store_format_valid"),
            F.col("dq_timestamp_valid").alias("timestamp_valid"),
            F.col("dq_items_valid").alias("items_valid"),
            F.col("data_quality_score").alias("quality_score")
        )
    )
    
    error_df = error_df.withColumn("error_timestamp", F.current_timestamp())
    
    return error_df

# COMMAND ----------

# MAGIC %md
# MAGIC ## Utility Functions for Monitoring

# COMMAND ----------

def log_processing_metrics():
    """Log key processing metrics for monitoring dashboards"""
    
    try:
        # This would integrate with your monitoring system
        print(f"POS Transactions Kafka Processing - {datetime.now()}")
        print(f"Topic: {KAFKA_TOPIC}")
        print(f"Bootstrap Servers: {KAFKA_BOOTSTRAP_SERVERS}")
        print(f"Checkpoint Location: {CHECKPOINT_LOCATION}")
        print("Processing streaming data...")
        
    except Exception as e:
        print(f"Error logging metrics: {str(e)}")

# Call logging function
log_processing_metrics()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Pipeline Health Check

# COMMAND ----------

def validate_pipeline_health():
    """Validate that the pipeline is running correctly"""
    
    try:
        # Check if we can connect to Kafka
        test_df = (
            spark.read
            .format("kafka")
            .option("kafka.bootstrap.servers", KAFKA_BOOTSTRAP_SERVERS)
            .option("subscribe", KAFKA_TOPIC)
            .option("startingOffsets", "latest")
            .option("endingOffsets", "latest")
            .load()
        )
        
        print("✓ Kafka connectivity verified")
        
        # Check target table schema
        try:
            existing_table = spark.table("bronze_streaming.pos_transactions")
            print("✓ Target table exists and accessible")
        except:
            print("ℹ Target table will be created on first run")
            
        return True
        
    except Exception as e:
        print(f"✗ Pipeline health check failed: {str(e)}")
        return False

# Run health check
validate_pipeline_health()